import { delay, http, HttpResponse } from "msw"

import { DEVICES_API_PATH } from "./api"
import type { Device } from "../model/types"

const devices: Device[] = [
  {
    id: "device-001",
    deviceName: "Line 1 Main PLC",
    deviceType: "PLC",
    deviceState: "normal",
    deviceConnectionStatus: "connected",
    groups: ["Production", "Line 1"],
    groupPaths: ["/factory-a/production/line-1"],
    activeProtocol: "Modbus TCP",
    supportedProtocols: ["Modbus TCP", "OPC UA"],
    protocolAdapter: "modbus-adapter",
    protocolInstance: "modbus-line-1",
    activeIpAddress: "10.20.1.11",
    isManaged: true,
    alertCount: 0,
    lastConnectedAt: "2026-05-14",
  },
  {
    id: "device-002",
    deviceName: "Assembly Robot A",
    deviceType: "Robot Controller",
    deviceState: "warning",
    deviceConnectionStatus: "connected",
    groups: ["Assembly", "Robotics"],
    groupPaths: ["/factory-a/assembly/robotics"],
    activeProtocol: "OPC UA",
    supportedProtocols: ["OPC UA", "EtherNet/IP"],
    protocolAdapter: "opcua-adapter",
    protocolInstance: "opcua-assembly-a",
    activeIpAddress: "10.20.2.24",
    isManaged: true,
    alertCount: 2,
    lastConnectedAt: "2026-05-14",
  },
  {
    id: "device-003",
    deviceName: "Environment Gateway",
    deviceType: "Sensor Gateway",
    deviceState: "offline",
    deviceConnectionStatus: "disconnected",
    groups: ["Utilities", "Environment"],
    groupPaths: ["/factory-a/utilities/environment"],
    activeProtocol: "MQTT",
    supportedProtocols: ["MQTT", "HTTP"],
    protocolAdapter: "mqtt-adapter",
    protocolInstance: "mqtt-env-gateway",
    activeIpAddress: "10.20.3.8",
    isManaged: false,
    alertCount: 5,
    lastConnectedAt: "2026-05-11",
  },
  {
    id: "device-004",
    deviceName: "Packaging HMI 01",
    deviceType: "HMI",
    deviceState: "normal",
    deviceConnectionStatus: "connecting",
    groups: ["Packaging", "Operator Stations"],
    groupPaths: ["/factory-b/packaging/operator-stations"],
    activeProtocol: "HTTP",
    supportedProtocols: ["HTTP", "WebSocket"],
    protocolAdapter: "http-adapter",
    protocolInstance: "http-packaging-hmi",
    activeIpAddress: "10.30.4.15",
    isManaged: true,
    alertCount: 1,
    lastConnectedAt: "2026-05-13",
  },
  {
    id: "device-005",
    deviceName: "Conveyor Drive 03",
    deviceType: "Drive",
    deviceState: "error",
    deviceConnectionStatus: "connected",
    groups: ["Material Handling", "Conveyors"],
    groupPaths: ["/factory-b/material-handling/conveyors"],
    activeProtocol: "EtherNet/IP",
    supportedProtocols: ["EtherNet/IP", "Modbus TCP"],
    protocolAdapter: "ethernet-ip-adapter",
    protocolInstance: "enip-conveyor-3",
    activeIpAddress: "10.30.5.31",
    isManaged: true,
    alertCount: 8,
    lastConnectedAt: "2026-05-14",
  },
  {
    id: "device-006",
    deviceName: "Line 2 Main PLC",
    deviceType: "PLC",
    deviceState: "normal",
    deviceConnectionStatus: "connected",
    groups: ["Production", "Line 2"],
    groupPaths: ["/factory-a/production/line-2"],
    activeProtocol: "Modbus TCP",
    supportedProtocols: ["Modbus TCP", "OPC UA"],
    protocolAdapter: "modbus-adapter",
    protocolInstance: "modbus-line-2",
    activeIpAddress: "10.20.1.12",
    isManaged: true,
    alertCount: 0,
    lastConnectedAt: "2026-05-14",
  },
  {
    id: "device-007",
    deviceName: "Assembly Robot B",
    deviceType: "Robot Controller",
    deviceState: "normal",
    deviceConnectionStatus: "connected",
    groups: ["Assembly", "Robotics"],
    groupPaths: ["/factory-a/assembly/robotics"],
    activeProtocol: "OPC UA",
    supportedProtocols: ["OPC UA", "EtherNet/IP"],
    protocolAdapter: "opcua-adapter",
    protocolInstance: "opcua-assembly-b",
    activeIpAddress: "10.20.2.25",
    isManaged: true,
    alertCount: 0,
    lastConnectedAt: "2026-05-14",
  },
  {
    id: "device-008",
    deviceName: "Temperature Sensor Hub",
    deviceType: "Sensor Gateway",
    deviceState: "warning",
    deviceConnectionStatus: "connected",
    groups: ["Utilities", "Environment"],
    groupPaths: ["/factory-a/utilities/environment"],
    activeProtocol: "MQTT",
    supportedProtocols: ["MQTT", "HTTP"],
    protocolAdapter: "mqtt-adapter",
    protocolInstance: "mqtt-temp-hub",
    activeIpAddress: "10.20.3.9",
    isManaged: true,
    alertCount: 3,
    lastConnectedAt: "2026-05-14",
  },
  {
    id: "device-009",
    deviceName: "Packaging HMI 02",
    deviceType: "HMI",
    deviceState: "normal",
    deviceConnectionStatus: "connected",
    groups: ["Packaging", "Operator Stations"],
    groupPaths: ["/factory-b/packaging/operator-stations"],
    activeProtocol: "HTTP",
    supportedProtocols: ["HTTP", "WebSocket"],
    protocolAdapter: "http-adapter",
    protocolInstance: "http-packaging-hmi-2",
    activeIpAddress: "10.30.4.16",
    isManaged: true,
    alertCount: 0,
    lastConnectedAt: "2026-05-14",
  },
  {
    id: "device-010",
    deviceName: "Conveyor Drive 04",
    deviceType: "Drive",
    deviceState: "normal",
    deviceConnectionStatus: "connected",
    groups: ["Material Handling", "Conveyors"],
    groupPaths: ["/factory-b/material-handling/conveyors"],
    activeProtocol: "EtherNet/IP",
    supportedProtocols: ["EtherNet/IP", "Modbus TCP"],
    protocolAdapter: "ethernet-ip-adapter",
    protocolInstance: "enip-conveyor-4",
    activeIpAddress: "10.30.5.32",
    isManaged: true,
    alertCount: 1,
    lastConnectedAt: "2026-05-13",
  },
  {
    id: "device-011",
    deviceName: "Mixer PLC",
    deviceType: "PLC",
    deviceState: "warning",
    deviceConnectionStatus: "connecting",
    groups: ["Production", "Mixing"],
    groupPaths: ["/factory-a/production/mixing"],
    activeProtocol: "OPC UA",
    supportedProtocols: ["OPC UA", "Modbus TCP"],
    protocolAdapter: "opcua-adapter",
    protocolInstance: "opcua-mixer",
    activeIpAddress: "10.20.6.18",
    isManaged: true,
    alertCount: 4,
    lastConnectedAt: "2026-05-12",
  },
  {
    id: "device-012",
    deviceName: "Boiler Controller",
    deviceType: "Controller",
    deviceState: "normal",
    deviceConnectionStatus: "connected",
    groups: ["Utilities", "Boiler Room"],
    groupPaths: ["/factory-a/utilities/boiler-room"],
    activeProtocol: "Modbus TCP",
    supportedProtocols: ["Modbus TCP"],
    protocolAdapter: "modbus-adapter",
    protocolInstance: "modbus-boiler",
    activeIpAddress: "10.20.7.21",
    isManaged: true,
    alertCount: 0,
    lastConnectedAt: "2026-05-14",
  },
  {
    id: "device-013",
    deviceName: "Quality Vision Station",
    deviceType: "Vision System",
    deviceState: "normal",
    deviceConnectionStatus: "connected",
    groups: ["Quality", "Inspection"],
    groupPaths: ["/factory-a/quality/inspection"],
    activeProtocol: "HTTP",
    supportedProtocols: ["HTTP", "WebSocket"],
    protocolAdapter: "http-adapter",
    protocolInstance: "http-vision-station",
    activeIpAddress: "10.20.8.44",
    isManaged: true,
    alertCount: 0,
    lastConnectedAt: "2026-05-14",
  },
  {
    id: "device-014",
    deviceName: "Warehouse Scanner Gateway",
    deviceType: "IoT Gateway",
    deviceState: "offline",
    deviceConnectionStatus: "disconnected",
    groups: ["Warehouse", "Receiving"],
    groupPaths: ["/factory-b/warehouse/receiving"],
    activeProtocol: "MQTT",
    supportedProtocols: ["MQTT", "HTTP"],
    protocolAdapter: "mqtt-adapter",
    protocolInstance: "mqtt-warehouse-scanner",
    activeIpAddress: "10.30.8.12",
    isManaged: false,
    alertCount: 6,
    lastConnectedAt: "2026-05-10",
  },
  {
    id: "device-015",
    deviceName: "Palletizer Robot",
    deviceType: "Robot Controller",
    deviceState: "normal",
    deviceConnectionStatus: "connected",
    groups: ["Packaging", "Palletizing"],
    groupPaths: ["/factory-b/packaging/palletizing"],
    activeProtocol: "EtherNet/IP",
    supportedProtocols: ["EtherNet/IP", "OPC UA"],
    protocolAdapter: "ethernet-ip-adapter",
    protocolInstance: "enip-palletizer",
    activeIpAddress: "10.30.9.20",
    isManaged: true,
    alertCount: 0,
    lastConnectedAt: "2026-05-14",
  },
  {
    id: "device-016",
    deviceName: "Label Printer 01",
    deviceType: "Printer",
    deviceState: "warning",
    deviceConnectionStatus: "connected",
    groups: ["Packaging", "Labeling"],
    groupPaths: ["/factory-b/packaging/labeling"],
    activeProtocol: "HTTP",
    supportedProtocols: ["HTTP"],
    protocolAdapter: "http-adapter",
    protocolInstance: "http-label-printer-1",
    activeIpAddress: "10.30.10.14",
    isManaged: true,
    alertCount: 2,
    lastConnectedAt: "2026-05-14",
  },
  {
    id: "device-017",
    deviceName: "Cooling Tower Monitor",
    deviceType: "Sensor Gateway",
    deviceState: "normal",
    deviceConnectionStatus: "connected",
    groups: ["Utilities", "Cooling"],
    groupPaths: ["/factory-a/utilities/cooling"],
    activeProtocol: "MQTT",
    supportedProtocols: ["MQTT", "OPC UA"],
    protocolAdapter: "mqtt-adapter",
    protocolInstance: "mqtt-cooling-monitor",
    activeIpAddress: "10.20.11.7",
    isManaged: true,
    alertCount: 0,
    lastConnectedAt: "2026-05-13",
  },
  {
    id: "device-018",
    deviceName: "Filling Line PLC",
    deviceType: "PLC",
    deviceState: "error",
    deviceConnectionStatus: "connected",
    groups: ["Production", "Filling"],
    groupPaths: ["/factory-a/production/filling"],
    activeProtocol: "Modbus TCP",
    supportedProtocols: ["Modbus TCP", "EtherNet/IP"],
    protocolAdapter: "modbus-adapter",
    protocolInstance: "modbus-filling-line",
    activeIpAddress: "10.20.12.19",
    isManaged: true,
    alertCount: 9,
    lastConnectedAt: "2026-05-14",
  },
  {
    id: "device-019",
    deviceName: "Maintenance Tablet Gateway",
    deviceType: "IoT Gateway",
    deviceState: "normal",
    deviceConnectionStatus: "connecting",
    groups: ["Maintenance", "Mobile"],
    groupPaths: ["/factory-a/maintenance/mobile"],
    activeProtocol: "HTTP",
    supportedProtocols: ["HTTP", "MQTT"],
    protocolAdapter: "http-adapter",
    protocolInstance: "http-maintenance-mobile",
    activeIpAddress: "10.20.13.5",
    isManaged: false,
    alertCount: 1,
    lastConnectedAt: "2026-05-12",
  },
  {
    id: "device-020",
    deviceName: "Shipping Scale",
    deviceType: "Scale",
    deviceState: "normal",
    deviceConnectionStatus: "connected",
    groups: ["Warehouse", "Shipping"],
    groupPaths: ["/factory-b/warehouse/shipping"],
    activeProtocol: "OPC UA",
    supportedProtocols: ["OPC UA", "Modbus TCP"],
    protocolAdapter: "opcua-adapter",
    protocolInstance: "opcua-shipping-scale",
    activeIpAddress: "10.30.14.22",
    isManaged: true,
    alertCount: 0,
    lastConnectedAt: "2026-05-14",
  },
]

export const devicesHandlers = [
  http.get(DEVICES_API_PATH, async () => {
    await delay(1000)

    return HttpResponse.json(devices)
  }),
]
