import { delay, http, HttpResponse } from "msw"

import { DEVICES_API_PATH } from "./api"
import type { Device } from "../model/types"

const devices: Device[] = [
  {
    deviceId: "1",
    deviceName: "Seoul-OUT-XL5-40CT-001",
    deviceType: "Bixolon XL Printer Series v4",
    complianceStatus: "Compliant",
    deviceState: "Green",
    connectionStatus: "DeviceOnline",
    groups: ["Seoul DC - Outbound"],
    groupPaths: ["/My Company/Korea Operations/Seoul DC/Outbound"],
    activeProtocol: "SOTI MQTT",
    supportedProtocols: ["SOTI MQTT", "HTTPS"],
    protocolAdapter: "Cloud-KR-PRN-MQTT-PA",
    protocolInstance: "mqtt-printer-seoul-outbound",
    activeIpAddress: "10.40.10.21",
  },
  {
    deviceId: "2",
    deviceName: "Seoul-OUT-XD7-20D-002",
    deviceType: "Bixolon XD7 Printer Series v4",
    complianceStatus: "Compliant",
    deviceState: "Green",
    connectionStatus: "DeviceOnline",
    groups: ["Seoul DC - Outbound"],
    groupPaths: ["/My Company/Korea Operations/Seoul DC/Outbound"],
    activeProtocol: "SOTI MQTT",
    supportedProtocols: ["SOTI MQTT", "HTTPS"],
    protocolAdapter: "Cloud-KR-PRN-MQTT-PA",
    protocolInstance: "mqtt-printer-seoul-outbound",
    activeIpAddress: "10.40.10.22",
  },
  {
    deviceId: "3",
    deviceName: "Seoul-IN-SRP-S300II-003",
    deviceType: "Bixolon SRP Printer Series v2",
    complianceStatus: "Compliant",
    deviceState: "Green",
    connectionStatus: "DeviceOnline",
    groups: ["Seoul DC - Receiving"],
    groupPaths: ["/My Company/Korea Operations/Seoul DC/Receiving"],
    activeProtocol: "HTTPS",
    supportedProtocols: ["HTTPS", "SOTI MQTT"],
    protocolAdapter: "Cloud-KR-PRN-HTTPS-PA",
    protocolInstance: "https-printer-seoul-receiving",
    activeIpAddress: "10.40.11.23",
  },
  {
    deviceId: "4",
    deviceName: "Seoul-IN-RK95-004",
    deviceType: "Barcode Scanner",
    complianceStatus: "Compliant",
    deviceState: "Green",
    connectionStatus: "DeviceOnline",
    groups: ["Seoul DC - Receiving"],
    groupPaths: ["/My Company/Korea Operations/Seoul DC/Receiving"],
    activeProtocol: "Android Enterprise",
    supportedProtocols: ["Android Enterprise", "HTTPS"],
    protocolAdapter: "Cloud-KR-AE-PA",
    protocolInstance: "android-enterprise-scanners",
    activeIpAddress: "10.40.11.24",
  },
  {
    deviceId: "5",
    deviceName: "Seoul-PACK-TAB-ACTIVE5-005",
    deviceType: "Rugged Tablet",
    complianceStatus: "Compliant",
    deviceState: "Green",
    connectionStatus: "DeviceOnline",
    groups: ["Seoul DC - Packing"],
    groupPaths: ["/My Company/Korea Operations/Seoul DC/Packing"],
    activeProtocol: "Android Enterprise",
    supportedProtocols: ["Android Enterprise", "SOTI MQTT"],
    protocolAdapter: "Cloud-KR-AE-PA",
    protocolInstance: "android-enterprise-tablets",
    activeIpAddress: "10.40.12.25",
  },
  {
    deviceId: "6",
    deviceName: "Seoul-PACK-PM45-006",
    deviceType: "Honeywell Label Printer",
    complianceStatus: "Pending",
    deviceState: "Yellow",
    connectionStatus: "DeviceOnline",
    groups: ["Seoul DC - Packing"],
    groupPaths: ["/My Company/Korea Operations/Seoul DC/Packing"],
    activeProtocol: "SNMP",
    supportedProtocols: ["SNMP", "HTTPS"],
    protocolAdapter: "Cloud-KR-PRN-SNMP-PA",
    protocolInstance: "snmp-printer-health",
    activeIpAddress: "10.40.12.26",
  },
  {
    deviceId: "7",
    deviceName: "Seoul-QA-MEMOR12-007",
    deviceType: "Mobile Computer",
    complianceStatus: "Compliant",
    deviceState: "Green",
    connectionStatus: "DeviceOnline",
    groups: ["Seoul DC - QA"],
    groupPaths: ["/My Company/Korea Operations/Seoul DC/QA"],
    activeProtocol: "Android Enterprise",
    supportedProtocols: ["Android Enterprise", "HTTPS"],
    protocolAdapter: "Cloud-KR-AE-PA",
    protocolInstance: "android-enterprise-handhelds",
    activeIpAddress: "10.40.13.27",
  },
  {
    deviceId: "8",
    deviceName: "Seoul-QA-XM7-40R-008",
    deviceType: "Bixolon XM7 Printer Series v4",
    complianceStatus: "Compliant",
    deviceState: "Green",
    connectionStatus: "DeviceOnline",
    groups: ["Seoul DC - QA"],
    groupPaths: ["/My Company/Korea Operations/Seoul DC/QA"],
    activeProtocol: "Bluetooth",
    supportedProtocols: ["Bluetooth", "SOTI MQTT"],
    protocolAdapter: "Cloud-KR-PRN-BT-PA",
    protocolInstance: "bt-mobile-printer",
    activeIpAddress: "10.40.13.28",
  },
  {
    deviceId: "9",
    deviceName: "Busan-OUT-ZT411-009",
    deviceType: "Zebra Industrial Printer",
    complianceStatus: "Compliant",
    deviceState: "Green",
    connectionStatus: "DeviceOnline",
    groups: ["Busan DC - Outbound"],
    groupPaths: ["/My Company/Korea Operations/Busan DC/Outbound"],
    activeProtocol: "Zebra Link-OS",
    supportedProtocols: ["Zebra Link-OS", "HTTPS"],
    protocolAdapter: "Cloud-KR-LINKOS-PA",
    protocolInstance: "linkos-industrial-printers",
    activeIpAddress: "10.41.10.31",
  },
  {
    deviceId: "10",
    deviceName: "Busan-OUT-XL5-40CT-010",
    deviceType: "Bixolon XL Printer Series v4",
    complianceStatus: "Compliant",
    deviceState: "Green",
    connectionStatus: "DeviceOnline",
    groups: ["Busan DC - Outbound"],
    groupPaths: ["/My Company/Korea Operations/Busan DC/Outbound"],
    activeProtocol: "SOTI MQTT",
    supportedProtocols: ["SOTI MQTT", "HTTPS"],
    protocolAdapter: "Cloud-KR-PRN-MQTT-PA",
    protocolInstance: "mqtt-printer-busan-outbound",
    activeIpAddress: "10.41.10.32",
  },
  {
    deviceId: "11",
    deviceName: "Busan-IN-RK95-011",
    deviceType: "Barcode Scanner",
    complianceStatus: "Compliant",
    deviceState: "Yellow",
    connectionStatus: "GatewayNotAvailable",
    groups: ["Busan DC - Receiving"],
    groupPaths: ["/My Company/Korea Operations/Busan DC/Receiving"],
    activeProtocol: "Android Enterprise",
    supportedProtocols: ["Android Enterprise", "HTTPS"],
    protocolAdapter: "Cloud-KR-AE-PA",
    protocolInstance: "android-enterprise-scanners",
    activeIpAddress: "10.41.11.33",
  },
  {
    deviceId: "12",
    deviceName: "Busan-IN-SRP-S300II-012",
    deviceType: "Bixolon SRP Printer Series v2",
    complianceStatus: "Compliant",
    deviceState: "Green",
    connectionStatus: "DeviceOnline",
    groups: ["Busan DC - Receiving"],
    groupPaths: ["/My Company/Korea Operations/Busan DC/Receiving"],
    activeProtocol: "HTTPS",
    supportedProtocols: ["HTTPS", "SOTI MQTT"],
    protocolAdapter: "Cloud-KR-PRN-HTTPS-PA",
    protocolInstance: "https-printer-busan-receiving",
    activeIpAddress: "10.41.11.34",
  },
  {
    deviceId: "13",
    deviceName: "Busan-PACK-TAB-ACTIVE5-013",
    deviceType: "Rugged Tablet",
    complianceStatus: "Pending",
    deviceState: "Yellow",
    connectionStatus: "DeviceOnline",
    groups: ["Busan DC - Packing"],
    groupPaths: ["/My Company/Korea Operations/Busan DC/Packing"],
    activeProtocol: "Android Enterprise",
    supportedProtocols: ["Android Enterprise", "SOTI MQTT"],
    protocolAdapter: "Cloud-KR-AE-PA",
    protocolInstance: "android-enterprise-tablets",
    activeIpAddress: "10.41.12.35",
  },
  {
    deviceId: "14",
    deviceName: "Busan-PACK-PM45-014",
    deviceType: "Honeywell Label Printer",
    complianceStatus: "Compliant",
    deviceState: "Green",
    connectionStatus: "ConnectionPending",
    groups: ["Busan DC - Packing"],
    groupPaths: ["/My Company/Korea Operations/Busan DC/Packing"],
    activeProtocol: "SNMP",
    supportedProtocols: ["SNMP", "HTTPS"],
    protocolAdapter: "Cloud-KR-PRN-SNMP-PA",
    protocolInstance: "snmp-printer-health",
    activeIpAddress: "10.41.12.36",
  },
  {
    deviceId: "15",
    deviceName: "Incheon-RET-KIOSK-015",
    deviceType: "Android Kiosk",
    complianceStatus: "Compliant",
    deviceState: "Green",
    connectionStatus: "DeviceOnline",
    groups: ["Incheon Retail - Front"],
    groupPaths: ["/My Company/Korea Retail/Incheon/Front"],
    activeProtocol: "Android Enterprise",
    supportedProtocols: ["Android Enterprise", "HTTPS"],
    protocolAdapter: "Cloud-KR-AE-PA",
    protocolInstance: "android-enterprise-kiosks",
    activeIpAddress: "10.42.20.41",
  },
  {
    deviceId: "16",
    deviceName: "Incheon-RET-SPP-L410-016",
    deviceType: "Mobile Printer",
    complianceStatus: "Compliant",
    deviceState: "Green",
    connectionStatus: "DeviceOnline",
    groups: ["Incheon Retail - Front"],
    groupPaths: ["/My Company/Korea Retail/Incheon/Front"],
    activeProtocol: "Bluetooth",
    supportedProtocols: ["Bluetooth", "SOTI MQTT"],
    protocolAdapter: "Cloud-KR-PRN-BT-PA",
    protocolInstance: "bt-mobile-printer",
    activeIpAddress: "10.42.20.42",
  },
  {
    deviceId: "17",
    deviceName: "Incheon-STOCK-MEMOR12-017",
    deviceType: "Mobile Computer",
    complianceStatus: "Compliant",
    deviceState: "Green",
    connectionStatus: "DeviceOnline",
    groups: ["Incheon Retail - Stockroom"],
    groupPaths: ["/My Company/Korea Retail/Incheon/Stockroom"],
    activeProtocol: "Android Enterprise",
    supportedProtocols: ["Android Enterprise", "HTTPS"],
    protocolAdapter: "Cloud-KR-AE-PA",
    protocolInstance: "android-enterprise-handhelds",
    activeIpAddress: "10.42.21.43",
  },
  {
    deviceId: "18",
    deviceName: "Incheon-STOCK-XD7-20D-018",
    deviceType: "Bixolon XD7 Printer Series v4",
    complianceStatus: "NonCompliant",
    deviceState: "Red",
    connectionStatus: "DeviceUnreachable",
    groups: ["Incheon Retail - Stockroom"],
    groupPaths: ["/My Company/Korea Retail/Incheon/Stockroom"],
    activeProtocol: "SOTI MQTT",
    supportedProtocols: ["SOTI MQTT", "HTTPS"],
    protocolAdapter: "Cloud-KR-PRN-MQTT-PA",
    protocolInstance: "mqtt-printer-retail",
    activeIpAddress: "",
  },
  {
    deviceId: "19",
    deviceName: "Daejeon-SVC-RELAY-019",
    deviceType: "SOTI Gateway",
    complianceStatus: "Compliant",
    deviceState: "Green",
    connectionStatus: "DeviceOnline",
    groups: ["Daejeon Service Center"],
    groupPaths: ["/My Company/Korea Operations/Daejeon Service Center"],
    activeProtocol: "HTTPS",
    supportedProtocols: ["HTTPS", "SOTI MQTT"],
    protocolAdapter: "Cloud-KR-GW-HTTPS-PA",
    protocolInstance: "gateway-daejeon-service",
    activeIpAddress: "10.43.30.51",
  },
  {
    deviceId: "20",
    deviceName: "Daejeon-SVC-PM45-020",
    deviceType: "Honeywell Label Printer",
    complianceStatus: "Compliant",
    deviceState: "Green",
    connectionStatus: "DeviceOnline",
    groups: ["Daejeon Service Center"],
    groupPaths: ["/My Company/Korea Operations/Daejeon Service Center"],
    activeProtocol: "SNMP",
    supportedProtocols: ["SNMP", "HTTPS"],
    protocolAdapter: "Cloud-KR-PRN-SNMP-PA",
    protocolInstance: "snmp-printer-health",
    activeIpAddress: "10.43.30.52",
  },
  {
    deviceId: "21",
    deviceName: "Daejeon-SVC-RK95-021",
    deviceType: "Barcode Scanner",
    complianceStatus: "Compliant",
    deviceState: "Green",
    connectionStatus: "DeviceOnline",
    groups: ["Daejeon Service Center"],
    groupPaths: ["/My Company/Korea Operations/Daejeon Service Center"],
    activeProtocol: "Android Enterprise",
    supportedProtocols: ["Android Enterprise", "HTTPS"],
    protocolAdapter: "Cloud-KR-AE-PA",
    protocolInstance: "android-enterprise-scanners",
    activeIpAddress: "10.43.30.53",
  },
  {
    deviceId: "22",
    deviceName: "Daegu-RET-KIOSK-022",
    deviceType: "Android Kiosk",
    complianceStatus: "Pending",
    deviceState: "Yellow",
    connectionStatus: "DeviceOnline",
    groups: ["Daegu Retail - Front"],
    groupPaths: ["/My Company/Korea Retail/Daegu/Front"],
    activeProtocol: "Android Enterprise",
    supportedProtocols: ["Android Enterprise", "HTTPS"],
    protocolAdapter: "Cloud-KR-AE-PA",
    protocolInstance: "android-enterprise-kiosks",
    activeIpAddress: "10.44.20.61",
  },
  {
    deviceId: "23",
    deviceName: "Daegu-RET-SPP-L410-023",
    deviceType: "Mobile Printer",
    complianceStatus: "Compliant",
    deviceState: "Green",
    connectionStatus: "NetworkUnknown",
    groups: ["Daegu Retail - Front"],
    groupPaths: ["/My Company/Korea Retail/Daegu/Front"],
    activeProtocol: "Bluetooth",
    supportedProtocols: ["Bluetooth", "SOTI MQTT"],
    protocolAdapter: "Cloud-KR-PRN-BT-PA",
    protocolInstance: "bt-mobile-printer",
    activeIpAddress: "10.44.20.62",
  },
  {
    deviceId: "24",
    deviceName: "Daegu-STOCK-MEMOR12-024",
    deviceType: "Mobile Computer",
    complianceStatus: "Compliant",
    deviceState: "Green",
    connectionStatus: "DeviceOnline",
    groups: ["Daegu Retail - Stockroom"],
    groupPaths: ["/My Company/Korea Retail/Daegu/Stockroom"],
    activeProtocol: "Android Enterprise",
    supportedProtocols: ["Android Enterprise", "HTTPS"],
    protocolAdapter: "Cloud-KR-AE-PA",
    protocolInstance: "android-enterprise-handhelds",
    activeIpAddress: "10.44.21.63",
  },
  {
    deviceId: "25",
    deviceName: "Gwangju-RET-KIOSK-025",
    deviceType: "Android Kiosk",
    complianceStatus: "Compliant",
    deviceState: "Green",
    connectionStatus: "DeviceOnline",
    groups: ["Gwangju Retail - Front"],
    groupPaths: ["/My Company/Korea Retail/Gwangju/Front"],
    activeProtocol: "Android Enterprise",
    supportedProtocols: ["Android Enterprise", "HTTPS"],
    protocolAdapter: "Cloud-KR-AE-PA",
    protocolInstance: "android-enterprise-kiosks",
    activeIpAddress: "10.45.20.71",
  },
  {
    deviceId: "26",
    deviceName: "Gwangju-RET-XM7-40R-026",
    deviceType: "Bixolon XM7 Printer Series v4",
    complianceStatus: "Compliant",
    deviceState: "Green",
    connectionStatus: "DeviceOnline",
    groups: ["Gwangju Retail - Front"],
    groupPaths: ["/My Company/Korea Retail/Gwangju/Front"],
    activeProtocol: "Bluetooth",
    supportedProtocols: ["Bluetooth", "SOTI MQTT"],
    protocolAdapter: "Cloud-KR-PRN-BT-PA",
    protocolInstance: "bt-mobile-printer",
    activeIpAddress: "10.45.20.72",
  },
  {
    deviceId: "27",
    deviceName: "Gwangju-STOCK-RK95-027",
    deviceType: "Barcode Scanner",
    complianceStatus: "Compliant",
    deviceState: "Yellow",
    connectionStatus: "GatewayNotAvailable",
    groups: ["Gwangju Retail - Stockroom"],
    groupPaths: ["/My Company/Korea Retail/Gwangju/Stockroom"],
    activeProtocol: "Android Enterprise",
    supportedProtocols: ["Android Enterprise", "HTTPS"],
    protocolAdapter: "Cloud-KR-AE-PA",
    protocolInstance: "android-enterprise-scanners",
    activeIpAddress: "10.45.21.73",
  },
  {
    deviceId: "28",
    deviceName: "Suwon-QA-TAB-ACTIVE5-028",
    deviceType: "Rugged Tablet",
    complianceStatus: "Compliant",
    deviceState: "Green",
    connectionStatus: "DeviceOnline",
    groups: ["Suwon QA Lab"],
    groupPaths: ["/My Company/Korea Operations/Suwon QA Lab"],
    activeProtocol: "Android Enterprise",
    supportedProtocols: ["Android Enterprise", "SOTI MQTT"],
    protocolAdapter: "Cloud-KR-AE-PA",
    protocolInstance: "android-enterprise-tablets",
    activeIpAddress: "10.46.40.81",
  },
  {
    deviceId: "29",
    deviceName: "Suwon-QA-ZT411-029",
    deviceType: "Zebra Industrial Printer",
    complianceStatus: "Pending",
    deviceState: "Yellow",
    connectionStatus: "DeviceOnline",
    groups: ["Suwon QA Lab"],
    groupPaths: ["/My Company/Korea Operations/Suwon QA Lab"],
    activeProtocol: "Zebra Link-OS",
    supportedProtocols: ["Zebra Link-OS", "HTTPS"],
    protocolAdapter: "Cloud-KR-LINKOS-PA",
    protocolInstance: "linkos-industrial-printers",
    activeIpAddress: "10.46.40.82",
  },
  {
    deviceId: "30",
    deviceName: "Suwon-QA-MEMOR12-030",
    deviceType: "Mobile Computer",
    complianceStatus: "Compliant",
    deviceState: "Green",
    connectionStatus: "DeviceOnline",
    groups: ["Suwon QA Lab"],
    groupPaths: ["/My Company/Korea Operations/Suwon QA Lab"],
    activeProtocol: "Android Enterprise",
    supportedProtocols: ["Android Enterprise", "HTTPS"],
    protocolAdapter: "Cloud-KR-AE-PA",
    protocolInstance: "android-enterprise-handhelds",
    activeIpAddress: "10.46.40.83",
  },
  {
    deviceId: "31",
    deviceName: "Ulsan-MFG-SCALE-031",
    deviceType: "Warehouse Scale",
    complianceStatus: "NotApplicable",
    deviceState: "Gray",
    connectionStatus: "DeviceOffline",
    groups: ["Ulsan Manufacturing - Line 1"],
    groupPaths: ["/My Company/Korea Manufacturing/Ulsan/Line 1"],
    activeProtocol: "SNMP",
    supportedProtocols: ["SNMP", "HTTPS"],
    protocolAdapter: "Cloud-KR-IOT-SNMP-PA",
    protocolInstance: "snmp-industrial-equipment",
    activeIpAddress: "",
  },
  {
    deviceId: "32",
    deviceName: "Ulsan-MFG-XL5-40CT-032",
    deviceType: "Bixolon XL Printer Series v4",
    complianceStatus: "Compliant",
    deviceState: "Green",
    connectionStatus: "DeviceOnline",
    groups: ["Ulsan Manufacturing - Line 1"],
    groupPaths: ["/My Company/Korea Manufacturing/Ulsan/Line 1"],
    activeProtocol: "SOTI MQTT",
    supportedProtocols: ["SOTI MQTT", "HTTPS"],
    protocolAdapter: "Cloud-KR-PRN-MQTT-PA",
    protocolInstance: "mqtt-printer-manufacturing",
    activeIpAddress: "10.47.50.91",
  },
  {
    deviceId: "33",
    deviceName: "Ulsan-MFG-TAB-ACTIVE5-033",
    deviceType: "Rugged Tablet",
    complianceStatus: "Compliant",
    deviceState: "Green",
    connectionStatus: "DeviceOnline",
    groups: ["Ulsan Manufacturing - Line 2"],
    groupPaths: ["/My Company/Korea Manufacturing/Ulsan/Line 2"],
    activeProtocol: "Android Enterprise",
    supportedProtocols: ["Android Enterprise", "SOTI MQTT"],
    protocolAdapter: "Cloud-KR-AE-PA",
    protocolInstance: "android-enterprise-tablets",
    activeIpAddress: "10.47.51.92",
  },
  {
    deviceId: "34",
    deviceName: "Ulsan-MFG-XD7-20D-034",
    deviceType: "Bixolon XD7 Printer Series v4",
    complianceStatus: "Compliant",
    deviceState: "Green",
    connectionStatus: "ConnectionPending",
    groups: ["Ulsan Manufacturing - Line 2"],
    groupPaths: ["/My Company/Korea Manufacturing/Ulsan/Line 2"],
    activeProtocol: "HTTPS",
    supportedProtocols: ["HTTPS", "SOTI MQTT"],
    protocolAdapter: "Cloud-KR-PRN-HTTPS-PA",
    protocolInstance: "https-printer-manufacturing",
    activeIpAddress: "10.47.51.93",
  },
  {
    deviceId: "35",
    deviceName: "Jeju-RET-KIOSK-035",
    deviceType: "Android Kiosk",
    complianceStatus: "Compliant",
    deviceState: "Green",
    connectionStatus: "DeviceOnline",
    groups: ["Jeju Retail - Front"],
    groupPaths: ["/My Company/Korea Retail/Jeju/Front"],
    activeProtocol: "Android Enterprise",
    supportedProtocols: ["Android Enterprise", "HTTPS"],
    protocolAdapter: "Cloud-KR-AE-PA",
    protocolInstance: "android-enterprise-kiosks",
    activeIpAddress: "10.48.20.101",
  },
  {
    deviceId: "36",
    deviceName: "Jeju-RET-SPP-L410-036",
    deviceType: "Mobile Printer",
    complianceStatus: "Compliant",
    deviceState: "Green",
    connectionStatus: "DeviceOnline",
    groups: ["Jeju Retail - Front"],
    groupPaths: ["/My Company/Korea Retail/Jeju/Front"],
    activeProtocol: "Bluetooth",
    supportedProtocols: ["Bluetooth", "SOTI MQTT"],
    protocolAdapter: "Cloud-KR-PRN-BT-PA",
    protocolInstance: "bt-mobile-printer",
    activeIpAddress: "10.48.20.102",
  },
  {
    deviceId: "37",
    deviceName: "Jeju-STOCK-MEMOR12-037",
    deviceType: "Mobile Computer",
    complianceStatus: "Pending",
    deviceState: "Yellow",
    connectionStatus: "DeviceOnline",
    groups: ["Jeju Retail - Stockroom"],
    groupPaths: ["/My Company/Korea Retail/Jeju/Stockroom"],
    activeProtocol: "Android Enterprise",
    supportedProtocols: ["Android Enterprise", "HTTPS"],
    protocolAdapter: "Cloud-KR-AE-PA",
    protocolInstance: "android-enterprise-handhelds",
    activeIpAddress: "10.48.21.103",
  },
  {
    deviceId: "38",
    deviceName: "Field-SVC-TAB-ACTIVE5-038",
    deviceType: "Rugged Tablet",
    complianceStatus: "Compliant",
    deviceState: "Green",
    connectionStatus: "DeviceOnline",
    groups: ["Field Service"],
    groupPaths: ["/My Company/Korea Operations/Field Service"],
    activeProtocol: "Android Enterprise",
    supportedProtocols: ["Android Enterprise", "SOTI MQTT"],
    protocolAdapter: "Cloud-KR-AE-PA",
    protocolInstance: "android-enterprise-field-service",
    activeIpAddress: "10.49.60.111",
  },
  {
    deviceId: "39",
    deviceName: "Field-SVC-SPP-L410-039",
    deviceType: "Mobile Printer",
    complianceStatus: "NonCompliant",
    deviceState: "Red",
    connectionStatus: "DeviceUnreachable",
    groups: ["Field Service"],
    groupPaths: ["/My Company/Korea Operations/Field Service"],
    activeProtocol: "Bluetooth",
    supportedProtocols: ["Bluetooth", "SOTI MQTT"],
    protocolAdapter: "Cloud-KR-PRN-BT-PA",
    protocolInstance: "bt-mobile-printer",
    activeIpAddress: "",
  },
  {
    deviceId: "40",
    deviceName: "Field-SVC-RK95-040",
    deviceType: "Barcode Scanner",
    complianceStatus: "Compliant",
    deviceState: "Green",
    connectionStatus: "DeviceOnline",
    groups: ["Field Service"],
    groupPaths: ["/My Company/Korea Operations/Field Service"],
    activeProtocol: "Android Enterprise",
    supportedProtocols: ["Android Enterprise", "HTTPS"],
    protocolAdapter: "Cloud-KR-AE-PA",
    protocolInstance: "android-enterprise-scanners",
    activeIpAddress: "10.49.60.113",
  },
  {
    deviceId: "41",
    deviceName: "Spare-Pool-XL5-40CT-041",
    deviceType: "Bixolon XL Printer Series v4",
    complianceStatus: "NotApplicable",
    deviceState: "Gray",
    connectionStatus: "DeviceOnline",
    groups: ["Spare Pool"],
    groupPaths: ["/My Company/Korea Operations/Spare Pool"],
    activeProtocol: "SOTI MQTT",
    supportedProtocols: ["SOTI MQTT", "HTTPS"],
    protocolAdapter: "Cloud-KR-PRN-MQTT-PA",
    protocolInstance: "mqtt-printer-spares",
    activeIpAddress: "10.50.70.121",
  },
  {
    deviceId: "42",
    deviceName: "Spare-Pool-XD7-20D-042",
    deviceType: "Bixolon XD7 Printer Series v4",
    complianceStatus: "NotApplicable",
    deviceState: "Gray",
    connectionStatus: "DeviceOnline",
    groups: ["Spare Pool"],
    groupPaths: ["/My Company/Korea Operations/Spare Pool"],
    activeProtocol: "HTTPS",
    supportedProtocols: ["HTTPS", "SOTI MQTT"],
    protocolAdapter: "Cloud-KR-PRN-HTTPS-PA",
    protocolInstance: "https-printer-spares",
    activeIpAddress: "10.50.70.122",
  },
  {
    deviceId: "43",
    deviceName: "NOC-GW-RELAY-043",
    deviceType: "SOTI Gateway",
    complianceStatus: "Compliant",
    deviceState: "Green",
    connectionStatus: "DeviceOnline",
    groups: ["Network Operations"],
    groupPaths: ["/My Company/Korea Operations/Network Operations"],
    activeProtocol: "HTTPS",
    supportedProtocols: ["HTTPS", "SOTI MQTT"],
    protocolAdapter: "Cloud-KR-GW-HTTPS-PA",
    protocolInstance: "gateway-network-operations",
    activeIpAddress: "10.51.80.131",
  },
  {
    deviceId: "44",
    deviceName: "NOC-GW-RELAY-044",
    deviceType: "SOTI Gateway",
    complianceStatus: "Compliant",
    deviceState: "Green",
    connectionStatus: "DeviceOnline",
    groups: ["Network Operations"],
    groupPaths: ["/My Company/Korea Operations/Network Operations"],
    activeProtocol: "HTTPS",
    supportedProtocols: ["HTTPS", "SOTI MQTT"],
    protocolAdapter: "Cloud-KR-GW-HTTPS-PA",
    protocolInstance: "gateway-network-operations",
    activeIpAddress: "10.51.80.132",
  },
  {
    deviceId: "45",
    deviceName: "NOC-MON-SCALE-045",
    deviceType: "Warehouse Scale",
    complianceStatus: "Pending",
    deviceState: "Yellow",
    connectionStatus: "DeviceOnline",
    groups: ["Network Operations"],
    groupPaths: ["/My Company/Korea Operations/Network Operations"],
    activeProtocol: "SNMP",
    supportedProtocols: ["SNMP", "HTTPS"],
    protocolAdapter: "Cloud-KR-IOT-SNMP-PA",
    protocolInstance: "snmp-industrial-equipment",
    activeIpAddress: "10.51.80.133",
  },
  {
    deviceId: "46",
    deviceName: "Seoul-OUT-ZT411-046",
    deviceType: "Zebra Industrial Printer",
    complianceStatus: "Compliant",
    deviceState: "Yellow",
    connectionStatus: "GatewayNotAvailable",
    groups: ["Seoul DC - Outbound"],
    groupPaths: ["/My Company/Korea Operations/Seoul DC/Outbound"],
    activeProtocol: "Zebra Link-OS",
    supportedProtocols: ["Zebra Link-OS", "HTTPS"],
    protocolAdapter: "Cloud-KR-LINKOS-PA",
    protocolInstance: "linkos-industrial-printers",
    activeIpAddress: "10.40.10.46",
  },
  {
    deviceId: "47",
    deviceName: "Busan-PACK-XM7-40R-047",
    deviceType: "Bixolon XM7 Printer Series v4",
    complianceStatus: "Compliant",
    deviceState: "Green",
    connectionStatus: "DeviceOnline",
    groups: ["Busan DC - Packing"],
    groupPaths: ["/My Company/Korea Operations/Busan DC/Packing"],
    activeProtocol: "Bluetooth",
    supportedProtocols: ["Bluetooth", "SOTI MQTT"],
    protocolAdapter: "Cloud-KR-PRN-BT-PA",
    protocolInstance: "bt-mobile-printer",
    activeIpAddress: "10.41.12.47",
  },
  {
    deviceId: "48",
    deviceName: "Incheon-STOCK-TAB-ACTIVE5-048",
    deviceType: "Rugged Tablet",
    complianceStatus: "Compliant",
    deviceState: "Green",
    connectionStatus: "ConnectionPending",
    groups: ["Incheon Retail - Stockroom"],
    groupPaths: ["/My Company/Korea Retail/Incheon/Stockroom"],
    activeProtocol: "Android Enterprise",
    supportedProtocols: ["Android Enterprise", "SOTI MQTT"],
    protocolAdapter: "Cloud-KR-AE-PA",
    protocolInstance: "android-enterprise-tablets",
    activeIpAddress: "10.42.21.48",
  },
  {
    deviceId: "49",
    deviceName: "Daegu-STOCK-ZT411-049",
    deviceType: "Zebra Industrial Printer",
    complianceStatus: "Compliant",
    deviceState: "Green",
    connectionStatus: "DeviceOnline",
    groups: ["Daegu Retail - Stockroom"],
    groupPaths: ["/My Company/Korea Retail/Daegu/Stockroom"],
    activeProtocol: "Zebra Link-OS",
    supportedProtocols: ["Zebra Link-OS", "HTTPS"],
    protocolAdapter: "Cloud-KR-LINKOS-PA",
    protocolInstance: "linkos-retail-printers",
    activeIpAddress: "10.44.21.49",
  },
  {
    deviceId: "50",
    deviceName: "Jeju-RET-RK95-050",
    deviceType: "Barcode Scanner",
    complianceStatus: "Compliant",
    deviceState: "Green",
    connectionStatus: "DeviceOnline",
    groups: ["Jeju Retail - Front"],
    groupPaths: ["/My Company/Korea Retail/Jeju/Front"],
    activeProtocol: "Android Enterprise",
    supportedProtocols: ["Android Enterprise", "HTTPS"],
    protocolAdapter: "Cloud-KR-AE-PA",
    protocolInstance: "android-enterprise-scanners",
    activeIpAddress: "10.48.20.150",
  },
]

export const devicesHandlers = [
  http.get(DEVICES_API_PATH, async () => {
    await delay(1000)

    return HttpResponse.json(devices)
  }),
]
